name: HopperItemSorter
version: '1.0'
main: com.github.zeddicuspl.hopperItemSorter.HopperItemSorter
api-version: '1.21'
authors: [ Zeddicus ]
description: Filter Hopper plugin
website: https://www.github.com/zeddicus-pl
